### ISSUE TITLE
Multi-line function arguments

### ISSUE THREAD

**Issue by cmichelenstrofer** [invenia/BlueStyle#111]
Anyone else bothered by the closing parentheses being on the same indentation level as the `function` and `end` keywords? Ideally I would prefer everything between these two keywords to be indented. 

Currently this is recommended, note the `)` at the same indent level as `function` and `end`, visually interrupting/splitting this block. 

```julia
# currently recommended
function foobar(
    df::DataFrame,
    id::Symbol,
    variable::Symbol,
    value::AbstractString,
    prefix::AbstractString="",
)
    # code
end
```

On the other hand, I do not like the idea of just indenting  the `)` on more level since then there is no visual separation between the function argument list and the code. I.e. 

```julia
# NO
function foobar(
    df::DataFrame,
    id::Symbol,
    variable::Symbol,
    value::AbstractString,
    prefix::AbstractString="",
    )
    # code
end
```

I also much prefer the recommended style over multiple arguments per line and arguments in the first line. I.e. 

```julia
# NO
function foobar(df::DataFrame, id::Symbol, variable::Symbol,
    value::AbstractString, prefix::AbstractString="",)
    # code
end
``` 

My suggestion would be: 
* indent the arguments *twice*. This should be fine since there is only one argument per line.
* indent the closing parenthesis once
E.g.

```julia
# YES
function foobar(
        df::DataFrame,
        id::Symbol,
        variable::Symbol,
        value::AbstractString,
        prefix::AbstractString="",
    )
    # code
end
```

This would be breaking though. Thoughts?

**Comment by iamed2** [comment]
I prefer the currently recommended version, since the trailing lines are an extension of the top line, which is at the left-most indentation level. I think this provides a good separation between the arguments and the first line of code without requiring a blank line (with the increased indentation level, I have seen people instinctively add another blank line before the code in order to provide visual separation). 

Why do you prefer the increased indentation?

**Comment by cmichelenstrofer** [comment]
Yeah, it is a matter of preference. And FWIW I prefer the approach here over that in the other styles. It was not the increased indentation that I prefer, but the absence of anything else between the `function` and `end` at the first indentation level. Just the visual interruption of that block. But might be just me.
