### ISSUE TITLE
Do we want whitespace around `//`

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/BlueStyle#63]
Currently guidance:
> Surround most binary operators with a single space on either side: ...
> Binary operators may be excluded from this guideline include: the range operator (`:`), rational operator (`//`), exponentiation operator (`^`)

But for the sake of implementing a formatter (#7, https://github.com/domluna/JuliaFormatter.jl/issues/283), do we prefer `1//2` or `1 // 2`?

**Comment by oxinabox** [comment]
1//2 is a single number

**Comment by oxinabox** [comment]
We want that it currently says
