### ISSUE TITLE
Prefer `return nothing` over bare `return`

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/BlueStyle#64]
I thought this was already the BlueStyle guidance, but i don't see it. 

Which is preferred?
(a)
```julia
function maybe_do_thing()
    # code 
    return
end
```
or
(b)
```julia
function maybe_do_thing()
    # code 
    return nothing
end
```

If we are agreed on option (b) already we should write it down and i'll add it to the to-do list in https://github.com/domluna/JuliaFormatter.jl/issues/283

**Comment by mattBrzezinski** [comment]
Personally I prefer the explicit style of option b.

**Comment by omus** [comment]
I would go as far as saying if a `return` statement is used a value should be explicitly returned even if that value is `nothing`
