### ISSUE TITLE
multi-line ternary operator

### ISSUE THREAD

**Issue by tk3369** [invenia/BlueStyle#97]
Blue:
> Ternary operators (`?:`) should generally only consume a single line.

While reviewing TypeDBClient.jl code, I have code like this:
```julia
    owner_req = thing_type === nothing ?
        ThingRequestBuilder.attribute_get_owners_req(iid) :
        ThingRequestBuilder.attribute_get_owners_req(iid, proto(thing_type))
```

Is it preferred to write it in the long if-condition form?
```julia
    owner_req = if  thing_type === nothing
        ThingRequestBuilder.attribute_get_owners_req(iid) 
    else
        ThingRequestBuilder.attribute_get_owners_req(iid, proto(thing_type))
    end
```

**Comment by oxinabox** [comment]
Correct.
It is preferred to write it in the long multiline if-else form

**Comment by mattBrzezinski** [comment]
Personally I think multi-line ternary looks cleaner. 🤷
